FORMAT: 1A
HOST: http://api.countmein.io

# countmein.io
countmein API

# Group Events
Events related resources of the **countmein API**

## Events Collection [/event]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Tuesday Futsal"
        }, {
          "id": 2, "name": "Thursday Futsal"
        }]

### Create an Event [POST]
+ Request (application/json)

        { "name": "Tuesday Futsal" }

+ Response 201 (application/json)

        { "id": "mpkndpqo", "name": "Tuesday Futsal" }

## Event [/event/{id}]
A single Event object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Event [GET]
+ Response 200 (application/json)

    + Body

            { "id": "mpkndpqo", "name": "Tuesday Futsal" }

### Remove a Note [DELETE]
+ Response 204

## Total Number of Events [/eventcount]

### Retrieves the total number of events [GET]
+ Response 200 (application/json)

    + Body
    
            { "total": 46000000000 }