FORMAT: 1A
HOST: http://api.countmein.io

# countmein.io
countmein API

# Group Events
Events related resources of the **countmein API**

## Events Collection [/event]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Tuesday Futsal"
        }, {
          "id": 2, "name": "Thursday Futsal"
        }]

### Create an Event [POST]
+ Request (application/json)

        { "name": "Tuesday Futsal" }

+ Response 201 (application/json)

        { "id": "mpkndpqo", "name": "Tuesday Futsal" }

## Event [/event/{id}]
A single Event object with all its details

+ Parameters
    + id (required, number, `mpkndpqo`) ... 8 character hash `id` of the Event to perform action with. Has example value.

### Retrieve a Event [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": "mpkndpqo",
                "name": "Tuesday Futsal",
                "date": "25 mar",
                "time": "12:30pm",
                "where": "kelvin grove fitness center",
                "organiserName": "David",
                "guests": [{
                    "name": "David",
                    "email": "david@flodge.com",
                    "attending": true
                }, {
                    "name": "Glen",
                    "email": "glen.arrowsmith@gmail.com",
                    "attending": true
                }, {
                    "name": "Max",
                    "email": "max@flodge.com",
                    "attending": false
                }],
                "createdAt": "2014-03-24T13:42:27+10:00"
            }

### Remove a Note [DELETE]
+ Response 204

## Total Number of Events [/eventcount]

### Retrieves the total number of events [GET]
+ Response 200 (application/json)

    + Body
    
            { "total": 1100000000 }